language: go
go: 1.9

sudo: required

install:
  - go get -u github.com/golang/lint/golint

script:
  - golint -set_exit_status
  - gofmt -l .
  - go vet .
  - ./validate.sh

notifications:
  email: false
