language: go
go: 1.9

sudo: false

before_install:
  - go get -t -v ./...

install:
  - go get -u github.com/golang/lint/golint
  - go get -u github.com/golang/dep/...
  - dep ensure

jobs:
  include:

    - stage: lint
      script:
        - golint -set_exit_status
        - gofmt -l .
        - go vet .

    - stage: changelog validation
      script: ./validate.sh

    - stage: unit test
      script:
        - go test $(glide novendor)

    - stage: build binary
      script:
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s" -a -installsuffix cgo -o effective-broccoli -v

    - stage: codecov
      script:
        - cat codecov.yml | curl --data-binary @- https://codecov.io/validate
        - go test -race -coverprofile=coverage.txt -covermode=atomic
      after_success:
        - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
