language: go
go: 1.9

sudo: false

install:
  - go get -u github.com/golang/lint/golint
  - go get -u github.com/golang/dep/...
  - dep ensure

jobs:
  include:
    - stage: lint
      script:
        - golint -set_exit_status
        - gofmt -l .
        - go vet .
    - stage: changelog validation
      script: ./validate.sh
    - stage: unit test
      script:
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s" -a -installsuffix cgo -o effective-broccoli -v

notifications:
  email: false
